version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: multiplaEscolha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/dat
volumes:
  postgres_data: